### ISSUE TITLE
Unable to find image 'ess-image:latest' locally

### ISSUE THREAD

**Issue by stealwin** [aleksey-vi/externals-scan-script#1]
Trying to execute on arm64
` └─$  sudo docker run --rm --name ess-container -v ./python3:/application -w /application ess-image ess.py --help
Unable to find image 'ess-image:latest' locally
docker: Error response from daemon: pull access denied for ess-image, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
`
previously commands from instructions was executed without errors

**Comment by aleksey-vi** [comment]
This error means that Docker cannot find an image named ess-image:latest on your local machine. Docker is trying to download this image from a remote repository, but you don't have access to it. You may have forgotten to log into your Docker account or provide the correct repository name. Please check that you have entered the correct login details and image name.
